apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  controllerUrl: "http://192.168.0.214:8090"
  account: "customer1"
  appName: "docker-desktop"
  serviceAccountName: appdynamics-cluster-agent
  image: "docker.io/appdynamics/cluster-agent:latest"
  logLevel: "DEBUG"
  logFileSizeMb: 5
  logFileBackups: 3
  stdoutLogging: "true"
  nsToMonitor: [default,dev,stage,prod]
  defaultAppName: "AI-PROD"
  instrumentationMethod: Env
  appNameStrategy: manual
  nsToInstrumentRegex: stage|dev|prod
  resourcesToInstrument: [Deployment,StatefulSet]
  imageInfo:
    java:
      image: "docker.io/appdynamics/java-agent:20.9.0"
      agentMountPath: /opt/appdynamics
  netvizInfo:
    bciEnabled: true
    port: 3892 
  instrumentationRules:
    - namespaceRegex: dev
      appName: AI-Dev-dockerdesktop
      language: java
      imageInfo:
        image: "docker.io/appdynamics/java-agent:20.9.0"
        agentMountPath: /opt/appdynamics
        imagePullPolicy: "IfNotPresent"
    - namespaceRegex: stage
      appName: AI-Stage-dockerdesktop
      language: java
      imageInfo:
        image: "docker.io/appdynamics/java-agent:20.6.0"
        agentMountPath: /opt/appdynamics

